#!/bin/bash
case $1 in
  on|1|true)
    echo "30">/sys/devices/system/cpu/intel_pstate/max_perf_pct
    ;;
  off|0|false)
    echo "100">/sys/devices/system/cpu/intel_pstate/max_perf_pct
    ;;
esac

