
export TERM="xterm-256color"


DOTDIR="/home/farzeen/.dotfiles"
source "$DOTDIR/environment_vars"

ZDOTDIR="$DOTDIR/zsh"
ZGEN_DIR="$ZDOTDIR/cache/zgen"
CACHE_DIR="$ZDOTDIR/cache"

source $ZDOTDIR/zim/init.zsh

# source every file in tweaks dir

if [[ ! -f $ZDOTDIR/cache/tweaks_cache ]]; then
  for i in $ZDOTDIR/tweaks/*; do
    cat "$i" >>! $ZDOTDIR/cache/tweaks_cache
  done
fi
source $ZDOTDIR/cache/tweaks_cache
# for i in $ZDOTDIR/tweaks/*; do
  # source $i
# done

